---
title: "COVID-19 in US"
subtitle: "Situational Analysis Report"
author: "Prepared by: [R Ottawa community](https://ivi-m.github.io/R-Ottawa/)"
date: "Last updated: `r format (Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float: true
    collapsed: true
  # flexdashboard::flex_dashboard:
  #   orientation: columns
  #   vertical_layout: fill
---

```{r readCov, include=F}
knitr::opts_chunk$set(echo = FALSE)
source("01-read.R")

dtGeo <- readGeo()
dtUS <- readCovidUS() 
dateMax<- dtUS$date %>% max %>% ymd; dateMax


```


# Introduction

This report is generated automatically. 

The COVID-19 data is taken from:   

- [Johns Hopkins University U.S. Coronavirus database](https://coronavirus.jhu.edu/us-map), which is available at this [GitHub repository](https://github.com/CSSEGISandData/COVID-19).

This database was last updated on `r dateMax`.

# Summary

```{r include=T}
cols <- c("confirmed", "deaths")

# . By state ----

dt <- dtUS[, lapply(.SD, sum), by=state, .SDcols=cols] 
dt


library(DT)
DT::datatable(dt)

```



## Analysis by state

<!-- ## Analysis by state {.tabset .tabset-fade} -->


```{r results='asis'}

for ( state in dtUS$state %>% unique ) {
  
  cat( paste0("\n\n### \n\n", state) )
  
  dt0 <- dtUS[state == state]
  
  
  dt <- dt0[, lapply(.SD, sum), by=city, .SDcols=cols] 
  dt %>%  print
  
  # DT::datatable(dt) %>% print
  knitr::kable(dt) %>% print
  
  dt0 <- dt0 %>% covid.reduceToTopNCitiesToday(12)
  
  g <- dt0[ date > dateMax - 30] %>% 
    ggplot() + 
    #facet_wrap( city ~ .) +
    # facet_wrap( reorder(city, lng) ~ .) +
    # facet_wrap( reorder(city, lng) ~ ., scales="free") +
    facet_wrap( reorder(city, -confirmed, scales="free") ~ .) +
    # facet_wrap( reorder(city, state) ~ .) +
    geom_line(aes(date, confirmed), col="orange") +
    geom_line(aes(date, deaths), col="red") +
    labs(
      title= paste0("Infected per day"),
      subtitle=paste0("State: ", state, ". Date: ", dateMax), 
      caption=paste0(
        "Cities are sorted by location\n", 
        "Data source: Johns Hopkins University U.S. Coronavirus database\n", 
        "Generated by R Ottawa"
      )
      
    )
  print(g)
  # g %>% print
 # ggsave(paste0("png/", dateMax, "-", state, ".png"))
}

```

